# Generated by Django 5.2 on 2025-05-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.CharField(db_column='userID', max_length=20, primary_key=True, serialize=False)),
                ('userPW', models.CharField(db_column='userPW', max_length=20)),
                ('createDate', models.DateTimeField(blank=True, db_column='createDate', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
