# Generated by Django 5.2 on 2025-05-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='userss',
        ),
    ]
