# Generated by Django 5.2 on 2025-05-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
