# Generated by Django 5.2 on 2025-05-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
