# Generated by Django 5.2 on 2025-05-12 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imageID', models.AutoField(db_column='imageID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='createDate')),
                ('viewCount', models.IntegerField(db_column='viewCount', default=0)),
                ('imageURL', models.ImageField(db_column='imageURL', upload_to='images/')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Historys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchDate', models.DateTimeField(auto_now_add=True, db_column='createDate')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('imageID', models.ForeignKey(db_column='imageID', on_delete=django.db.models.deletion.DO_NOTHING, to='image.images')),
            ],
            options={
                'db_table': 'historys',
                'managed': True,
                'unique_together': {('userID', 'imageID')},
            },
        ),
        migrations.CreateModel(
            name='Favoriteimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='createDate')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('imageID', models.ForeignKey(db_column='imageID', on_delete=django.db.models.deletion.DO_NOTHING, to='image.images')),
            ],
            options={
                'db_table': 'favoriteimages',
                'managed': True,
                'unique_together': {('userID', 'imageID')},
            },
        ),
        migrations.CreateModel(
            name='Modimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(db_column='imageURL', upload_to='images/')),
                ('title', models.CharField(max_length=20)),
                ('imageID', models.ForeignKey(db_column='imageID', on_delete=django.db.models.deletion.DO_NOTHING, to='image.images')),
            ],
            options={
                'db_table': 'modimages',
                'managed': True,
                'unique_together': {('imageID', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('imageID', models.ForeignKey(db_column='imageID', on_delete=django.db.models.deletion.DO_NOTHING, to='image.images')),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
                'unique_together': {('imageID', 'tag')},
            },
        ),
    ]
