# Generated by Django 5.2 on 2025-05-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favoriteimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, db_column='createDate')),
            ],
            options={
                'db_table': 'favoriteimages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchdate', models.DateTimeField(auto_now_add=True, db_column='createDate')),
            ],
            options={
                'db_table': 'historys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imageid', models.AutoField(db_column='imageID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('createdate', models.DateTimeField(auto_now_add=True, db_column='createDate')),
                ('viewcount', models.IntegerField(db_column='viewCount', default=0)),
                ('imageurl', models.ImageField(db_column='imageURL', upload_to='images/')),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.ImageField(db_column='imageURL', upload_to='images/')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'modimages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
    ]
