# Generated by Django 5.2 on 2025-05-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'managed': True},
        ),
    ]
