# Generated by Django 5.2 on 2025-05-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_images_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'managed': False},
        ),
    ]
